### ISSUE TITLE
Unable to install: Error in Description file 

### ISSUE THREAD

**Issue by adamsorbie** [microsud/microbiomeutilities#119]
When trying to install I get the following error 
 `Error in read.dcf(path) : 
      Found continuation line starting '    person("Sudarsha ...' at begin of record.`

**Comment by microsud** [comment]
Hi @adamsorbie - Thanks for getting in touch. The current version requires R to be installed in any drive other than the C: drive due to administrator issues. The current solution is to install R in any drive other than the C: drive and then install the packages. This can be a difficult task but you can use this [script](https://github.com/microsud/Microbial-bioinformatics-introductory-course-Material-2018/blob/master/scripts/setup_microbiome_analysis.R) to install many packages used for microbiome analysis after re-installing R. 

Best wishes,
Sudarshan
