### ISSUE TITLE
A

### ISSUE THREAD

**Issue by cafferychen777** [microsud/microbiomeutilities#187]
A

**Comment by antagomir** [comment]
Thanks! The microbiomeutilities pkg connections are more for @microsud to comment but I wanted to mention here our other relevant project. 

In summary, this is building a new framework based on the Bioconductor [TreeSummarizedExperiment](https://f1000research.com/articles/9-1246) data container (an alternative to phyloseq) and [MultiAssayExperiment](https://aacrjournals.org/cancerres/article/77/21/e39/662607/Software-for-the-Integration-of-Multiomics) data container. These are state-of-the-art solutions for managing multi-assay/multi-omic data collections and the [OMA gitbook](https://microbiome.github.io/OMA) (beta version) documents their use in the context of microbiome research. There is also an initial package [miaTime](https://microbiome.github.io/miaTime/) for time series, although it is still rather small package. 

This is a community-driven development project that links directly to other areas of development in Bioconductor, such as single cell omics, transcriptomics, metabolomics etc that are now increasingly adopting those same multi-omic containers.

If you are interested in syncing the MicrobiomeStat methods with this broader ecosystem of interoperable tools, we are open to discussing this further. Nevertheless, we will also have a look on how to take advantage of MicrobiomeStat but the interoperability between data handling should be solved somehow.

**Comment by cafferychen777** [comment]
Dear @antagomir ,

Thank you for your comprehensive response and for providing insights into your ongoing projects and development frameworks.

I am writing on behalf of the MicrobiomeStat development team, and we are thrilled to hear about the potential for interoperability and collaboration. We understand the significance of ensuring seamless data handling and integration, particularly within the extensive and diverse landscape of microbiome research.

I am pleased to inform you that we already have a function implemented that can convert a MultiAssayExperiment object to a data object. Given the context and the nature of your work, we are ready to proceed in creating a function for TreeSummarizedExperiment to be converted into an mStat object. This would be in line with the conversion functions we already have, such as:

- mStat_convert_DESeqDataSet_to_data_obj(): Converts a DESeqDataSet Object to a MicrobiomeStat Data Object
- mStat_convert_DGEList_to_data_obj(): Converts a DGEList Object to a MicrobiomeStat Data Object
- mStat_convert_MRExperiment_to_data_obj(): Converts an MRExperiment Object to a MicrobiomeStat Data Object
- mStat_convert_MultiAssayExperiment_to_data_obj(): Converts MultiAssayExperiment Object to a Data Object
- etc.

Our readiness to expand on these conversion capabilities reflects our commitment to promoting versatile and effective tools for the microbiome research community. We believe that the integration of MicrobiomeStat with your TreeSummarizedExperiment and MultiAssayExperiment data containers would facilitate more coherent and inclusive analyses for researchers across the globe.

Thank you once again for considering MicrobiomeStat for collaboration, and we look forward to furthering this exciting partnership.

Best regards,
Chen YANG

**Comment by antagomir** [comment]
Great!

Could you consider directly supporting TreeSummarizedExperiment/MultiAssayExperiment in the MicrobiomeStat package? At simplest, this could mean allowing these as input, and converting them to other custom data class internally in the functions.

The advantage would be that the MicrobiomeStat would become directly interoperable with the broader Bioconductor package ecosystem, without the need to do extra conversion steps. It would also support interoperability of MicrobiomeStat outputs with those frameworks in the same way.

**Comment by cafferychen777** [comment]
Hi @antagomir ,

Thank you for sharing the OMA gitbook (beta version) documents. I've had a chance to review it and I'm really impressed with the comprehensive information and structure.

I wanted to propose the idea of interlinking our Gitbooks. We have documented our work at MicrobiomeStat on our own Gitbook page ([MicrobiomeStat Gitbook](https://www.microbiomestat.wiki/)). I believe it would be mutually beneficial for both of our communities to cross-reference our resources. This could provide our users with broader perspectives and additional resources, fostering a more connected and collaborative ecosystem.

Additionally, I noticed the mention of LinDA in your content. It might be worthwhile to consider including a description of LinDA in your DAA methods. As outlined in "LinDA: linear models for differential abundance analysis of microbiome compositional data" ([Read the Paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02655-5)), LinDA is noted to surpass ANCOM-BC and ANCOM-BC2, offering a more robust and effective solution for differential abundance analysis. This could be a valuable addition to your package, enhancing its capabilities for your users.

Looking forward to your thoughts on these suggestions.

Best,
Chen YANG

**Comment by cafferychen777** [comment]
Hi @antagomir ,

Thank you for your insightful suggestion!

At this juncture, we might not be able to incorporate direct support for TreeSummarizedExperiment/MultiAssayExperiment in the MicrobiomeStat package. My current understanding indicates that the utilization of these formats is not widespread. This makes it challenging to justify the integration effort given the limited audience, as the workload might not yield corresponding benefits.

I am also eager to comprehend the specific advantages that these formats have over others like phyloseq. Your insights would be valuable in this aspect. It is imperative to fully grasp these benefits before embarking on integration to ensure that the step adds considerable value to MicrobiomeStat and its community.

Our current priority is to maintain a uniform and effective data structure within MicrobiomeStat by using mStat. However, we are not closing doors on potential adjustments in the future. As the usage of TreeSummarizedExperiment/MultiAssayExperiment formats grows and demonstrates clear advantages, we will certainly consider revisiting this decision and evaluate the feasibility of integration to enhance the functionality and interoperability of MicrobiomeStat.

Your understanding and continued dialogue on this matter are highly appreciated. Thank you for contributing to the enhancement of the MicrobiomeStat package.

Best regards,
Chen YANG

**Comment by antagomir** [comment]
1) We can cross-link but it may be difficult to do more within OMA without TreeSE/MAE data container support.

2) LinDA is discussed in a dedicated subsection [11.2.5 in OMA](https://microbiome.github.io/OMA/differential-abundance.html), although that could be expanded.

3) The (Tree)SummarizedExperiment and MultiAssayExperiment data containers differ crucially from phyloseq, mStat, and other classes in one aspect: they are directly developed and supported by the core Bioconductor ecosystem and used across multiple different application areas. This framework is newer and hence the package ecosystem is still shaping up but it may tell something that SummarizedExperiment (published in 2015) and MultiAssayExperiment (published in 2017) downloads rank 15/2230 (top <1%) and 89/2230 (top <5%) in Bioconductor, respectively. They are thus already among some of the most supported formats. These containers are newer and based on 15 years of experience on how optimized multi-table data containers should be designed. The key idea is that instead of everyone developing their own data solutions, the community can improve interoperability and reduce overlapping efforts by supporting the same commonly agreed containers. The phyloseq has been extremely useful for the field but the only added value that is has is that it has been around for a longer time, and hence gathered many supporting packages around it. TreeSummarizedExperiment provides same capabilities than phyloseq but additionally supports the integration of multiple assays (e.g. different statistical transformations, multiple taxonomic levels), sparse matrices (i.e. higher scalability to larger data collections), hierarchies/taxonomies also in sample space (not just feature spaces), in some cases higher speed, and links directly to closely related single cell package ecosystem that provides a number of further analysis and visualization tools.  I did 10 years of development around phyloseq (the microbiome package, which still ranks in top-10% Bioc downloads as of today) and switched to TreeSE with some others since 2020 due to these benefits.

**Comment by microsud** [comment]
@cafferychen777 Not very impressed with your comments in directing users to your tool by creating issues on repos of other developers without first discussing with them first. For example, in another package by @david-barnett #https://github.com/david-barnett/microViz/discussions/124 you create similar issue and write it without mentioning the fact that you are developer of the microbiomeStat software and write it as if it is an independent recommendation. I highly recommend users to follow the latest community developed open-source framework standards within the miaverse.

Edit: I see similar post on microbiome R package github repo: https://github.com/microbiome/microbiome/issues/219

**Comment by antagomir** [comment]
We could perhaps move the discussion from above to a better suited platform, like OMA issues?
